@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3MTUxMjM5MDcsImV4cCI6MTcxNTEyNzUwN30.r9gDI3JYsAvUaVzsoltaz-tQVM0AKbKfeHu1dviuJBs


### Order: Create
POST {{host}}/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "orderId": "12345678912345",
    "name": "Daniel User",
    "total": 3,
    "productList": ["112345"]
}


### Order: Get
GET {{host}}/order
Authorization: Bearer {{token}}

### Order: Get higthest total
GET {{host}}/order/highest-amount-sold
Authorization: Bearer {{token}}

### Order: Get sold orders for date
GET {{host}}/order/total-sold-price/2024-05-01T00:00:00Z/2024-05-30T00:00:00Z
Authorization: Bearer {{token}}


### Order: Update 2022-03-01T00:00:00Z
PATCH {{host}}/order/123456789123
Authorization: Bearer {{token}}
Content-Type: application/json

{    
    "name": "Daniel User updated",
    "productList": ["1123456", "112345", "1123455"]
}

