@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3MTUxMDQzODIsImV4cCI6MTcxNTEwNzk4Mn0.K09RjmR944RckX7p4egAi2dmO5UZCxoRnxmTeO4QNU0


### Order: Create
POST {{host}}/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "orderId": "1234567891234",
    "name": "Daniel User",
    "total": 3,
    "productList": ["112345", "1123455", "11234567"]
}


### Order: Get
GET {{host}}/order
Authorization: Bearer {{token}}

### Order: Get higthest total
GET {{host}}/order/highest-amount-sold
Authorization: Bearer {{token}}

### Order: Update
PATCH {{host}}/order/123456789123
Authorization: Bearer {{token}}
Content-Type: application/json

{    
    "name": "Daniel User updated",
    "productList": ["1123456", "112345", "1123455"]
}
