@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiYWRtaW4iLCJpYXQiOjE3MTUwNDQxNzIsImV4cCI6MTcxNTA0Nzc3Mn0.6_R0s-6LKx8UCeGa-sExePy_pm_hOB1BQuuw8g6TtaY

### Product: Create
POST {{host}}/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sku": "112345",
    "name": "PrimerProduct2",
    "price": 3,
    "picture": "4"
}

### Product: Get
GET {{host}}/product/112345
Authorization: Bearer {{token}}

### Product: GetAll
GET {{host}}/product
Authorization: Bearer {{token}}

### Product: Update
PATCH {{host}}/product/112345
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "price": 5,
    "picture": "updatedPicture"
}

### Product: Delete
DELETE {{host}}/product/112345
Authorization: Bearer {{token}}